const express = require('express')
const port = 9000
const userRouter = require('./routers/userRouter')
const addressRouter = require('./routers/addressRouter')
const adminRouter = require('./routers/adminRouter')
const categoryRouter = require('./routers/categoryRouter')
const booksRouter = require('./routers/booksRouter')
const cartRouter = require('./routers/cartRouter')
const paymentRouter = require('./routers/paymentRouter')
const shippingRouter = require('./routers/shippingRouter')
const orderRouter = require('./routers/orderRouter')
const orderDetailRouter = require('./routers/orderDetailRouter')
const cors = require('cors')

const app = express()
app.use(express.json())
app.use(cors())

app.use(userRouter)
app.use(addressRouter)
app.use(adminRouter)
app.use(categoryRouter)
app.use(booksRouter)
app.use(cartRouter)
app.use(paymentRouter)
app.use(shippingRouter)
app.use(orderRouter)
app.use(orderDetailRouter)

app.listen(port, () => {
    console.log('App running on port ' + port)
})